version: "3.9"

services:
  mapforge-eureka:
    build: ./mapforge-eureka
    container_name: mapforge-eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - microservices-net

  db-core:
    image: postgres:17
    container_name: db-core
    environment:
      POSTGRES_DB: MapForge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - core_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MapForge"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-net

  db-gameplay:
    image: postgres:17
    container_name: db-gameplay
    environment:
      POSTGRES_DB: MapForgeGameplay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - gameplay_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MapForgeGameplay"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - microservices-net

  mapforge-core:
    build: ./mapforge-core
    container_name: mapforge-core
    environment:
      - DOCKER_DB_URL=jdbc:postgresql://db-core:5432/MapForge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      mapforge-eureka:
        condition: service_healthy
      db-core:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - microservices-net

  mapforge-gameplay:
    build: ./mapforge-gameplay
    container_name: mapforge-gameplay
    environment:
      - DOCKER_DB_URL=jdbc:postgresql://db-gameplay:5432/MapForgeGameplay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      mapforge-eureka:
        condition: service_healthy
      db-gameplay:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - microservices-net

  mapforge-gateway:
    build: ./mapforge-gateway
    container_name: mapforge-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://mapforge-eureka:8761/eureka/
    depends_on:
      mapforge-eureka:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  core_data:
  gameplay_data: