--liquibase sql

--changeset Eduard:15

ALTER TABLE characters ADD COLUMN created_at DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE campaigns ADD COLUMN created_at DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE campaign_actors ADD COLUMN created_at DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE campaign_members ADD COLUMN created_at DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE maps ADD COLUMN created_at DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE npcs ADD COLUMN created_at DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE attack_actions ADD COLUMN created_at TIMESTAMP DEFAULT NOW() NOT NULL;;
ALTER TABLE movement_actions ADD COLUMN created_at TIMESTAMP DEFAULT NOW() NOT NULL;;